import fs from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import type { AppConfig } from "../config.js";
import type { Database } from "../lib/database.js";
import { panelHostnames } from "./panel-domains.js";
import { stableContainerName } from "./runtime-identity.js";

function routeName(id: string): string {
  return id.replace(/[^a-zA-Z0-9-]/g, "-");
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

export function reconcileRouting(config: AppConfig, database: Database): void {
  // Failed deletions remain visible in the control plane for an explicit retry,
  // but are quarantined from traffic along with active deletion jobs.
  const projects = database.listRoutableProjects();
  const previews = database.listRoutablePullRequestPreviews();
  const panelDomains = panelHostnames(database);
  const lines: string[] = [
    "# Generated by Shelter. Manual changes will be overwritten.",
    "http:",
    "  routers:"
  ];

  if (panelDomains.length > 0) {
    lines.push(
      "    panel:",
      `      rule: ${yamlString(panelDomains.map((domain) => `Host(\`${domain}\`)`).join(" || "))}`,
      "      entryPoints: [web]",
      "      service: panel",
      "      middlewares: [secure-headers, compress]"
    );
  }

  for (const project of projects) {
    if (!project.active_deployment_id || !database.getDeployment(project.active_deployment_id)?.internal_port) continue;
    const domains = database.listDomains(project.id).filter((domain) => domain.status === "active");
    if (domains.length === 0) continue;
    const name = routeName(project.id);
    const hostRule = domains.map((domain) => `Host(\`${domain.hostname}\`)`).join(" || ");
    lines.push(
      `    ${name}:`,
      `      rule: ${yamlString(hostRule)}`,
      "      entryPoints: [web]",
      `      service: ${name}`,
      "      middlewares: [secure-headers, compress]"
    );
  }

  for (const preview of previews) {
    if (!preview.active_deployment_id) continue;
    const deployment = database.getDeployment(preview.active_deployment_id);
    if (!deployment?.runtime_container || !deployment.internal_port) continue;
    const name = routeName(preview.id);
    lines.push(
      `    ${name}:`,
      `      rule: ${yamlString(`Host(\`${preview.hostname}\`)`)}`,
      "      entryPoints: [web]",
      `      service: ${name}`,
      "      middlewares: [secure-headers, compress]"
    );
  }

  if (panelDomains.length === 0 && previews.length === 0 && projects.every((project) => (
    !project.active_deployment_id ||
    !database.getDeployment(project.active_deployment_id)?.internal_port ||
    database.listDomains(project.id).every((domain) => domain.status !== "active")
  ))) {
    lines.push("    noop:", "      rule: \"Host(`never.invalid`)\"", "      service: noop");
  }

  lines.push("  services:");
  if (panelDomains.length > 0) {
    lines.push(
      "    panel:",
      "      loadBalancer:",
      "        servers:",
      "          - url: \"http://api:7080\""
    );
  }

  let hasAppService = false;
  for (const project of projects) {
    if (
      !project.active_deployment_id ||
      database.listDomains(project.id).every((domain) => domain.status !== "active")
    ) continue;
    const activeDeployment = database.getDeployment(project.active_deployment_id);
    if (!activeDeployment?.internal_port) continue;
    hasAppService = true;
    const name = routeName(project.id);
    lines.push(
      `    ${name}:`,
      "      loadBalancer:",
      "        passHostHeader: true",
      "        servers:",
      `          - url: ${yamlString(`http://${activeDeployment.runtime_container ?? stableContainerName(project.slug, activeDeployment.image_tag)}:${activeDeployment.internal_port}`)}`
    );
  }

  for (const preview of previews) {
    if (!preview.active_deployment_id) continue;
    const deployment = database.getDeployment(preview.active_deployment_id);
    if (!deployment?.runtime_container || !deployment.internal_port) continue;
    hasAppService = true;
    const name = routeName(preview.id);
    lines.push(
      `    ${name}:`,
      "      loadBalancer:",
      "        passHostHeader: true",
      "        servers:",
      `          - url: ${yamlString(`http://${deployment.runtime_container}:${deployment.internal_port}`)}`
    );
  }

  if (panelDomains.length === 0 && !hasAppService) {
    lines.push(
      "    noop:",
      "      loadBalancer:",
      "        servers:",
      "          - url: \"http://127.0.0.1:9\""
    );
  }

  lines.push(
    "  middlewares:",
    "    compress:",
    "      compress: {}",
    "    secure-headers:",
    "      headers:",
    "        contentTypeNosniff: true",
    "        referrerPolicy: \"strict-origin-when-cross-origin\"",
    "        frameDeny: true"
  );

  fs.mkdirSync(path.dirname(config.traefikConfigPath), { recursive: true, mode: 0o700 });
  const temporaryPath = `${config.traefikConfigPath}.${process.pid}.${randomUUID()}.tmp`;
  fs.writeFileSync(temporaryPath, `${lines.join("\n")}\n`, { mode: 0o600 });
  fs.renameSync(temporaryPath, config.traefikConfigPath);
}
